# Setup
title: na-che-x
tagline: Nancy's Experimental Website
url: https://na-che-x.github.io
paginate: 5
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Nancy Xia
  url: https://na-che-x.github.io/
  email: sapphoinseattle@gmail.com

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/poole/poole
